name: CD with Truffle

# push 이벤트가 발생할 때 실행
on:
  push:
    branches:
      - main  # main 브랜치에 push가 될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Ganache Docker 컨테이너 실행
      - name: Run Ganache Docker container
        run: |
          docker run -d -p 7545:7545 trufflesuite/ganache-cli:latest

      # 2. Truffle 설치
      - name: Install Truffle
        run: npm install -g truffle

      # 3. 프로젝트 의존성 설치
      - name: Install dependencies
        run: npm install
             npm install -g truffle solc@0.8.20  # solc 버전 지정하여 설치

      # 4. Truffle 컴파일
      - name: Compile Truffle contracts
        run: truffle compile

      # 5. 스마트 계약 배포 (이미 있는 truffle-config.js 파일을 사용)
      - name: Migrate contracts with Truffle
        run: truffle migrate --network development

      # 6. Docker 이미지 빌드 및 푸시
      - name: Docker build & push to Docker repo
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/bc .
          docker push ${{ secrets.DOCKER_REPO }}/bc

      # 7. 기존에 실행되는 컨테이너 모두 멈추고 새 이미지를 pull 후 실행
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker stop $(docker ps -a -q)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/bc
            sudo docker-compose up --build -d
            sudo docker image prune -f
