name: Deploy Ganache and Truffle on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      id: deploy
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          # 프로젝트 디렉토리 생성
          mkdir -p /home/ubuntu/project
          cd /home/ubuntu/project || git clone https://github.com/<username>/<repository>.git .
          git pull origin main

          # Docker Compose 실행
          docker-compose down || true
          docker-compose up -d --build
