name: Deploy Ganache and Truffle on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      id: deploy
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        envs: GITHUB_SHA
        script: |
          # Move to project directory or clone repository
          cd /home/ubuntu/project || git clone https://github.com/<username>/<repository>.git /home/ubuntu/project
          cd /home/ubuntu/project

          # Pull latest changes
          git pull origin main

          # Stop existing containers and rebuild
          docker-compose down || true
          docker-compose up -d --build
