name: Deploy with Ganache and Truffle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker container
      run: |
        docker build -t ganache-truffle .
        docker run -d --name ganache -p 8545:8545 trufflesuite/ganache:latest
        docker ps

    - name: Install dependencies
      run: |
        docker exec ganache npm install -g truffle

    - name: Deploy contracts using Truffle
      run: |
        docker exec ganache truffle compile
        docker exec ganache truffle migrate --network development

    - name: Verify deployment
      run: |
        docker exec ganache truffle test
