name: Deploy Ganache and Truffle on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KEY }}

    - name: Copy project to EC2
      run: |
        scp -r . ec2-user@${{ secrets.HOST }}:/home/ubuntu/project

    - name: SSH into EC2 and run deployment script
      run: |
        ssh ec2-user@${{ secrets.HOST }} << 'EOF'
          cd /home/ubuntu/project
          docker-compose down || true
          docker-compose up -d --build
        EOF
